name: Auto-merge tscircuitbot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]
# github.event.pull_request.user.login == 'tscircuitbot' && 
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      
      contains(github.event.pull_request.title, 'chore: update @tscircuit/core')
    
    steps:
      - name: Wait for all required checks
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Wait for type check completion
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: type-check
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Wait for format check completion
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: format-check
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.TSCIRCUIT_BOT_GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash